<template>
  <div>
    <docs-function v-for="func in functions" :func="func" :key="func.name"></docs-function>
  </div>
</template>

<script>
  import DocsFunction from "../content/DocsFunction";
  export default {
    name: "SchemeLilypondDocs",
    data() {
      return {
        functions: [
          {
            name: 'make-phrase',
            desc: 'Converts a given melody to a timed phrase.',
            arguments: [['melody', 'in note numbers'], ['rhythm', 'in note length numbers (list must be the same length as the number of notes)']],
            syntax: '(make-phrase melody rhythm)'
          },
          {
            name: 'make-parallel',
            desc: 'Combines two or more voices into a parallel structure.',
            arguments: [['phrases', 'accepts two or more phrases of note number/note length pairs']],
            syntax: '(make-parallel phrases)'
          },
          {
            name: 'note-to-number',
            desc: 'Translates a note name to a note number.',
            arguments: [['note', 'is an absolute note as a note name (a, b, c etc)']],
            syntax: '(note-to-number note)'
          },
          {
            name: 'notes-to-numbers',
            desc: 'Translates a list of absolute note names to note numbers.',
            arguments: [['notes', 'notes is a list of notes']],
            syntax: '(notes-to-numbers notes)'
          },
          {
            name: 'transpose-natural',
            desc: 'Transposes a natural note symbolically.',
            arguments: [['note', 'is a natural note as a note name'], ['steps', 'is the number of natural notes to transpose by (a + 2 = c)']],
            syntax: '(transpose-natural note steps)'
          },
          {
            name: 'transpose-naturals',
            desc: 'Transposes a list of natural notes symbolically.',
            arguments: [['melody', 'is a list of natural notes'], ['steps', 'is the amount of natural tones to transpose by']],
            syntax: '(make-phrase melody rhythm)'
          },
          {
            name: 'transpose-note',
            desc: 'Transposes a natural note numerically.',
            arguments: [['note', 'is a natural note as a note number'], ['steps', 'is the number of semitones to transpose by']],
            syntax: '(transpose-note note steps)'
          },
          {
            name: 'transpose-phrase',
            desc: 'Transposes a phrase from make-phrase numerically.',
            arguments: [['phrase', 'is the output of make-phrase'], ['steps', 'is the number of semitones to transpose by']],
            syntax: '(make-phrase phrase steps)'
          },
          {
            name: 'scale-note-length',
            desc: 'Scales the length of a given note by a given factor.',
            arguments: [['note', 'is a note in the form of (note length)'], ['factor', 'is the scale factor to be used']],
            syntax: '(scale-note-length note factor)'
          },
          {
            name: 'scale-length',
            desc: 'Scales the lengths of all notes in a given phrase.',
            arguments: [['phrase', 'is a list of timed notes generated by make-phrase'], ['factor', 'is the scale factor to be used']],
            syntax: '(scale-length phrase factor)'
          },
          {
            name: 'merge-phrases',
            desc: 'Merges two or more phrases into a single phrase.',
            arguments: [['phrase', 'is a list of note/length pairs. Note: this function needs at least two instances of phrase to execute']],
            syntax: '(merge-phrases [phrases])'
          },
          {
            name: 'merge-phraselist',
            desc: 'Merges a list of phrases into a single phrase.',
            arguments: [['phrases', 'is a list that contains two or more phrases.']],
            syntax: '(merge-phraselist phrases)'
          },
          {
            name: 'repeat-phrase',
            desc: 'Helper function. Repeats a phrase a given number of times.',
            arguments: [['phrase', 'is a phrase that should be repeated'], ['repeats', 'is the number of times a given phrase should be repeated']],
            syntax: '(repeat-phrase phrase repeats)'
          },
          {
            name: 'reverse-phrase',
            desc: 'Reverses a given phrase.',
            arguments: [['phrase', 'is a phrase that should be reversed']],
            syntax: '(reverse-phrase phrase)'
          },
          {
            name: 'apply-transform',
            desc: 'Applies (a) transformation function(s) to a list of notes. Note: all arguments must be supplied, either with values or as an empty expression \'().',
            arguments: [['list', 'is a list of notes to transform'], ['parallel-function', 'is the function to be applied to every parallel block'], ['serial-function', 'is the function to be applied to every serial block'], ['note-function', 'is the function to be applied to every note']],
            syntax: '(apply-transform list parallel-function serial-function note-function)'
          }
        ]
      }
    }
  }
</script>

<style scoped>

</style>